spring:
  config:
    activate:
      on-profile: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql

  jpa:
    hibernate:
      ddl-auto: none
